package pl.chemia.game

val spicyDeck = listOf(
    GameCard("s01","CONNECTION",1,3,"Pierwsze skojarzenie","Powiedz partnerowi, co jako pierwsze przyciągnęło Twoją uwagę, kiedy go poznałeś."),
    GameCard("s02","CONNECTION",1,3,"Najlepszy detal","Wskaż jedną drobną rzecz w partnerze, która działa na Ciebie bardziej, niż on przypuszcza."),
    GameCard("s03","FLIRT",1,4,"Komplement bez banału","Powiedz komplement, którego partner jeszcze dziś nie usłyszał."),
    GameCard("s04","FLIRT",1,4,"Spojrzenie","Patrzcie sobie w oczy przez 20 sekund bez mówienia."),
    GameCard("s05","TOUCH",1,4,"Dłoń","Trzymajcie się za dłonie przez 30 sekund i nie odrywajcie wzroku."),
    GameCard("s06","QUESTION",1,3,"Co lubisz najbardziej?","Powiedz, jaki rodzaj czułości najbardziej poprawia Ci nastrój."),
    GameCard("s07","QUESTION",1,3,"Idealny klimat","Wybierz: półmrok, muzyka, cisza czy spontaniczność. Wyjaśnij dlaczego."),
    GameCard("s08","FLIRT",1,4,"Szept","Powiedz partnerowi szeptem jedno zdanie, które ma go zaciekawić."),
    GameCard("s09","TOUCH",1,4,"Kark i ramiona","Zrób partnerowi 30-sekundowy masaż karku i ramion."),
    GameCard("s10","CONNECTION",1,3,"Jedna rzecz","Powiedz jedną rzecz, której chcesz dziś między Wami więcej."),
    GameCard("s11","FLIRT",1,4,"Pochwała","Opisz partnera trzema słowami, które brzmią jak zaproszenie na randkę."),
    GameCard("s12","ROLEPLAY",1,4,"Pierwsze spotkanie","Przez minutę zachowujcie się tak, jakbyście dopiero się poznali."),

    GameCard("p01","QUESTION",2,6,"Co buduje napięcie?","Powiedz, co najbardziej buduje u Ciebie napięcie: słowa, spojrzenie, dotyk czy oczekiwanie."),
    GameCard("p02","FLIRT",2,6,"Zakazane zdanie","Powiedz partnerowi jedno zdanie, którego normalnie nie powiedziałbyś przy innych."),
    GameCard("p03","KISS",2,7,"Wybór pocałunku","Partner wybiera: krótki pocałunek, długi pocałunek albo trzy pocałunki w wybrane miejsce powyżej ramion."),
    GameCard("p04","TOUCH",2,7,"Powolny dotyk","Przez 30 sekund prowadź dłoń po ramieniu, karku lub plecach partnera. Partner wybiera miejsce."),
    GameCard("p05","QUESTION",2,6,"Fantazja randkowa","Opowiedz o randce lub scenariuszu, który od dawna chodzi Ci po głowie."),
    GameCard("p06","ROLEPLAY",2,7,"Nieznajomi przy barze","Jedno z Was zaczyna rozmowę, jakbyście byli nieznajomymi spotkanymi wieczorem."),
    GameCard("p07","FLIRT",2,6,"Trzy słowa","Powiedz trzy słowa opisujące atmosferę, której chcesz dziś między Wami."),
    GameCard("p08","KISS",2,7,"Pocałunek z pauzą","Pocałuj partnera, przerwij na pięć sekund i pozwól jemu zdecydować, czy chce kontynuować."),
    GameCard("p09","QUESTION",2,6,"Gdzie lubisz czułość?","Wymień dwa miejsca na ciele, w których najbardziej lubisz niewinny, czuły dotyk."),
    GameCard("p10","TOUCH",2,7,"Masaż dłoni","Zrób powolny masaż dłoni partnera przez minutę."),
    GameCard("p11","FLIRT",2,6,"Najbardziej kuszące","Powiedz partnerowi, co w jego wyglądzie jest dziś dla Ciebie najbardziej kuszące."),
    GameCard("p12","ROLEPLAY",2,7,"Sekretna wiadomość","Napisz lub powiedz jedno krótkie zdanie, jakby było sekretną wiadomością wysłaną w środku nocy."),
    GameCard("p13","QUESTION",2,6,"Tempo","Wybierz: powoli i długo czy szybko i spontanicznie. Powiedz, co dziś bardziej Ci odpowiada."),
    GameCard("p14","KISS",2,7,"Partner wybiera","Partner wskazuje jedno miejsce na twarzy lub szyi, gdzie chce dostać pocałunek."),
    GameCard("p15","TOUCH",2,7,"Zamknięte oczy","Jedna osoba zamyka oczy, druga dotyka jej dłoni, karku albo ramion. Zgadnij miejsce."),
    GameCard("p16","FLIRT",2,6,"Głos","Powiedz to samo zdanie dwa razy: najpierw normalnie, potem najbardziej uwodzicielsko, jak potrafisz."),
    GameCard("p17","QUESTION",2,6,"Czego chcesz więcej?","Powiedz, czego chcesz dziś więcej: rozmowy, pocałunków, bliskości czy zabawy."),
    GameCard("p18","ROLEPLAY",2,7,"Hotel","Udawajcie przez 60 sekund, że spotkaliście się przypadkiem w hotelowym lobby."),
    GameCard("p19","CONNECTION",2,5,"Najlepsze wspomnienie","Przypomnijcie sobie moment, kiedy napięcie między Wami było wyjątkowo mocne."),
    GameCard("p20","FLIRT",2,6,"Jedno polecenie","Daj partnerowi jedno lekkie, flirtujące polecenie. Może odmówić lub zmienić je bez wyjaśnienia."),

    GameCard("h01","KISS",3,9,"Minuta pocałunków","Jeśli oboje chcecie, całujcie się przez minutę bez używania telefonu."),
    GameCard("h02","TOUCH",3,9,"Masaż pleców","Zrób partnerowi dwuminutowy, powolny masaż pleców przez ubranie lub bez niego — tylko w granicach, które oboje akceptujecie."),
    GameCard("h03","QUESTION",3,8,"Najodważniejsza fantazja","Opowiedz o jednej fantazji, o której możesz mówić komfortowo. Partner tylko słucha, bez oceniania."),
    GameCard("h04","ROLEPLAY",3,9,"Zakaz znajomości","Przez dwie minuty nie używajcie swoich imion i udawajcie, że właśnie się poznaliście."),
    GameCard("h05","FLIRT",3,8,"Szept do ucha","Powiedz partnerowi do ucha, co najbardziej chciałbyś, żeby zrobił później — bez presji na realizację."),
    GameCard("h06","TOUCH",3,9,"Mapa dotyku","Partner wskazuje trzy miejsca na ciele, gdzie lubi dotyk. Wybierz jedno z nich na 30 sekund."),
    GameCard("h07","KISS",3,9,"Powolnie","Pocałuj partnera tak wolno, jak potrafisz, i zatrzymaj się, gdy tylko on tego chce."),
    GameCard("h08","QUESTION",3,8,"Tak / może / nie","Wymieńcie po jednej rzeczy z kategorii: tak, może kiedyś, zdecydowanie nie."),
    GameCard("h09","ROLEPLAY",3,9,"Osoba publiczna","Jedno z Was udaje osobę bardzo pewną siebie, drugie próbuje ją poderwać."),
    GameCard("h10","FLIRT",3,8,"Bez dotyku","Przez minutę buduj napięcie wyłącznie słowami i spojrzeniem — bez dotykania."),
    GameCard("h11","TOUCH",3,9,"Partner prowadzi","Partner mówi: wolniej, szybciej, stop albo dalej podczas masażu karku, ramion lub pleców."),
    GameCard("h12","QUESTION",3,8,"Co Cię zaskoczyło?","Powiedz, co w partnerze okazało się bardziej pociągające z czasem niż na początku."),
    GameCard("h13","KISS",3,9,"Seria","Partner wybiera trzy miejsca: policzek, szyja, czoło, usta. Pocałuj je w wybranej kolejności."),
    GameCard("h14","ROLEPLAY",3,9,"Spóźniona randka","Jedna osoba czekała na randkę. Druga właśnie przyszła i musi ją przekonać, żeby została."),
    GameCard("h15","FLIRT",3,8,"Prawie bez słów","Możesz użyć tylko pięciu słów, żeby powiedzieć partnerowi, czego dziś chcesz."),
    GameCard("h16","TOUCH",3,9,"60 sekund","Przez 60 sekund jedna osoba wybiera tempo czułego dotyku, druga może w każdej chwili powiedzieć stop."),
    GameCard("h17","QUESTION",3,8,"Co chciałbyś usłyszeć?","Powiedz jedno zdanie, które szczególnie lubisz słyszeć od partnera w intymnym momencie."),
    GameCard("h18","KISS",3,9,"Przerwana scena","Zacznijcie się całować, zatrzymajcie po 20 sekundach i każde mówi, czy chce kontynuować."),
    GameCard("h19","ROLEPLAY",3,9,"Tajemnica","Jedno z Was zna sekret. Drugie ma minutę, żeby go wydobyć wyłącznie flirtem."),
    GameCard("h20","QUESTION",3,8,"Granica","Powiedz jedną granicę, która daje Ci większe poczucie bezpieczeństwa i przez to pozwala bardziej się otworzyć."),

    GameCard("x01","QUESTION",4,11,"Bez filtra","Powiedz partnerowi jedną odważną rzecz, której pragniesz, ale wcześniej nie umiałeś powiedzieć wprost."),
    GameCard("x02","ROLEPLAY",4,12,"Pełna scena","Wymyślcie role, miejsce i jeden zakaz. Zagrajcie scenę przez trzy minuty, zatrzymując ją natychmiast na każde „stop”."),
    GameCard("x03","TOUCH",4,12,"Zasłonięte oczy","Jeśli oboje chcecie, jedna osoba zamyka oczy, druga prowadzi powolny dotyk wyłącznie w wcześniej uzgodnionych miejscach."),
    GameCard("x04","KISS",4,12,"Bez pośpiechu","Jeśli oboje chcecie, poświęćcie dwie minuty wyłącznie na pocałunki i bliskość."),
    GameCard("x05","QUESTION",4,11,"Najmocniejsze napięcie","Opowiedz o sytuacji między Wami, kiedy pożądanie było najsilniejsze."),
    GameCard("x06","FLIRT",4,11,"Rozkaz i wybór","Daj partnerowi dwa odważne, ale zgodne z Waszymi granicami wybory. To on decyduje, czy wybiera któryś z nich."),
    GameCard("x07","ROLEPLAY",4,12,"Pierwszy raz","Zagrajcie, że to Wasze pierwsze spotkanie i oboje bardzo chcecie zrobić na sobie wrażenie."),
    GameCard("x08","QUESTION",4,11,"Lista TAK","Każde z Was podaje po dwie rzeczy, na które dziś zdecydowanie ma ochotę."),
    GameCard("x09","TOUCH",4,12,"Prowadzenie dłoni","Jedna osoba prowadzi dłoń partnera do miejsca, gdzie chce czułości. Druga podąża tylko za tym prowadzeniem."),
    GameCard("x10","KISS",4,12,"Stop-klatka","Pocałujcie się, a jedna osoba w dowolnym momencie mówi „stop”. Zatrzymajcie się natychmiast i zamieńcie role."),
    GameCard("x11","QUESTION",4,11,"Jedno pragnienie","Powiedz jedno konkretne pragnienie na dzisiejszy wieczór. Odpowiedź partnera może brzmieć: tak, może albo nie."),
    GameCard("x12","ROLEPLAY",4,12,"Władza oddana dobrowolnie","Jedna osoba prowadzi kolejną minutę flirtu i bliskości, ale każda instrukcja wymaga wyraźnego „tak”."),
    GameCard("x13","FLIRT",4,11,"Słowa zamiast dotyku","Powiedz partnerowi dokładnie, co w nim najbardziej Cię dziś pociąga. Nie dotykaj go przez minutę."),
    GameCard("x14","QUESTION",4,11,"Nowa rzecz","Wymień jedną nową rzecz, którą kiedyś chcielibyście wspólnie sprawdzić, bez zobowiązania do robienia jej dziś."),
    GameCard("x15","TOUCH",4,12,"Masaż z instrukcją","Partner wybiera obszar masażu i wydaje tylko cztery komendy: wolniej, szybciej, mocniej, stop."),
    GameCard("x16","KISS",4,12,"Partner decyduje","Partner decyduje, gdzie i jak długo chce być całowany. Ty wykonujesz tylko to, na co wyraźnie się zgodzi."),
    GameCard("x17","QUESTION",4,11,"Co jest najbardziej sexy?","Powiedz jedną cechę zachowania partnera, która działa na Ciebie najmocniej."),
    GameCard("x18","ROLEPLAY",4,12,"Po zamknięciu","Zagrajcie scenę, w której zostaliście sami po zamknięciu lokalu. Resztę historii tworzycie razem."),
    GameCard("x19","CONNECTION",4,10,"Po wszystkim","Powiedz, czego potrzebujesz po intensywnym momencie: przytulenia, rozmowy, ciszy, wody czy przestrzeni."),
    GameCard("x20","QUESTION",4,11,"Ostatnia karta","Każde z Was mówi jedną rzecz, którą chce kontynuować, i jedną, którą chce zakończyć na dziś.")
)
